FROM erctl:full

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

WORKDIR /app

COPY ./code/Energy-Aware-Entity-Resolution/models /app/models
COPY ./code/Energy-Aware-Entity-Resolution/main_distribution.py /app/main_distribution.py