apiVersion: batch/v1
kind: Job
metadata:
  name: calculating-similarity
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        app: calculating-similarity
    spec:
      restartPolicy: Never
      containers:
        - name: main
          image: __IMAGE_REPOSITORY__:embedding
          imagePullPolicy: Always
          command: [/opt/venv/bin/python, /app/entries/worker/calculating_similarity.py]
          args:
            - --workload
            - ""
          env:
          resources:
            requests:
              cpu: "1"
              memory: 2Gi
            limits:
              cpu: "2"
              memory: 4Gi
          volumeMounts:
            - name: pipeline-config
              mountPath: /app/config/examples/config-embedding.yaml
              subPath: config.yaml
            - name: worker-calculating-similarity
              mountPath: /app/entries/worker/calculating_similarity.py
              subPath: calculating_similarity.py
            - name: pipeline-buffer-data
              mountPath: /app/data/buffers
            - name: pipeline-io
              mountPath: /app/utils/pipeline_io.py
              subPath: pipeline_io.py
      volumes:
        - name: pipeline-config
          configMap:
            name: er-pipeline-config
        - name: worker-calculating-similarity
          configMap:
            name: eaer-worker-calculating-similarity
        - name: pipeline-buffer-data
          persistentVolumeClaim:
            claimName: pipeline-buffer-data-claim
        - name: pipeline-io
          configMap:
            name: eaer-pipeline-io
