apiVersion: batch/v1
kind: Job
metadata:
  name: candidate-enumeration
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        app: candidate-enumeration
    spec:
      restartPolicy: Never
      containers:
        - name: main
          image: __IMAGE_REPOSITORY__:featureindex
          imagePullPolicy: Always
          command: [/opt/venv/bin/python, /app/entries/worker/candidate_enumeration.py]
          args:
            - --workload
            - ""
          env:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: pipeline-config
              mountPath: /app/config/examples/config-embedding.yaml
              subPath: config.yaml
            - name: worker-candidate-enumeration
              mountPath: /app/entries/worker/candidate_enumeration.py
              subPath: candidate_enumeration.py
            - name: pipeline-feature-index-cache
              mountPath: /app/data/index
            - name: pipeline-buffer-data
              mountPath: /app/data/buffers
            - name: pipeline-io
              mountPath: /app/utils/pipeline_io.py
              subPath: pipeline_io.py
      volumes:
        - name: pipeline-config
          configMap:
            name: er-pipeline-config
        - name: worker-candidate-enumeration
          configMap:
            name: eaer-worker-candidate-enumeration
        - name: pipeline-feature-index-cache
          persistentVolumeClaim:
            claimName: pipeline-feature-index-cache-claim
        - name: pipeline-io
          configMap:
            name: eaer-pipeline-io
        - name: pipeline-buffer-data
          persistentVolumeClaim:
            claimName: pipeline-buffer-data-claim
