apiVersion: batch/v1
kind: Job
metadata:
  name: decision-making
  labels:
    app: decision-making
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        app: decision-making
    spec:
      restartPolicy: Never
      containers:
        - name: main
          image: __IMAGE_REPOSITORY__:prediction
          imagePullPolicy: Always
          command: [/opt/venv/bin/python, /app/entries/worker/decision_making.py]
          args:
            - --workload
            - ""
          env:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: pipeline-config
              mountPath: /app/config/examples/config-embedding.yaml
              subPath: config.yaml
            - name: worker-decision-making
              mountPath: /app/entries/worker/decision_making.py
              subPath: decision_making.py
            - name: pipeline-embedding-model-cache
              mountPath: /app/data/embedding
            - name: pipeline-decision-evaluation-cache
              mountPath: /app/data/predicted
            - name: pipeline-buffer-data
              mountPath: /app/data/buffers
            - name: pipeline-io
              mountPath: /app/utils/pipeline_io.py
              subPath: pipeline_io.py
      volumes:
        - name: pipeline-config
          configMap:
            name: er-pipeline-config
        - name: worker-decision-making
          configMap:
            name: eaer-worker-decision-making
        - name: pipeline-embedding-model-cache
          persistentVolumeClaim:
            claimName: pipeline-embedding-model-cache-claim
        - name: pipeline-decision-evaluation-cache
          persistentVolumeClaim:
            claimName: pipeline-decision-evaluation-cache-claim
        - name: pipeline-io
          configMap:
            name: eaer-pipeline-io
        - name: pipeline-buffer-data
          persistentVolumeClaim:
            claimName: pipeline-buffer-data-claim
