apiVersion: batch/v1
kind: Job
metadata:
  name: evaluation
  labels:
    app: evaluation
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: evaluation
    spec:
      restartPolicy: OnFailure
      containers:
        - name: main
          image: __IMAGE_REPOSITORY__:prediction
          imagePullPolicy: Always
          command: [/opt/venv/bin/python, /app/entries/worker/evaluation.py]
          args:
            - --workload
            - ""
          env:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: pipeline-config
              mountPath: /app/config/examples/config-embedding.yaml
              subPath: config.yaml
            - name: worker-evaluation
              mountPath: /app/entries/worker/evaluation.py
              subPath: evaluation.py
            - name: pipeline-data
              mountPath: /data
              readOnly: true
            - name: pipeline-communication
              mountPath: /app/data/communication
            - name: pipeline-buffer-data
              mountPath: /app/data/buffers
            - name: pipeline-io
              mountPath: /app/utils/pipeline_io.py
              subPath: pipeline_io.py
      volumes:
        - name: pipeline-config
          configMap:
            name: er-pipeline-config
        - name: worker-evaluation
          configMap:
            name: eaer-worker-evaluation
        - name: pipeline-data
          persistentVolumeClaim:
            claimName: pipeline-data-claim
        - name: pipeline-communication
          persistentVolumeClaim:
            claimName: pipeline-communication-claim
        - name: pipeline-io
          configMap:
            name: eaer-pipeline-io
        - name: pipeline-buffer-data
          persistentVolumeClaim:
            claimName: pipeline-buffer-data-claim
