# USELESS IMAGE

FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    msr-tools \
    libc-bin \
    linux-perf \
    nethogs \
    git \
    make \
    build-essential \
    sudo \
    && rm -rf /var/lib/apt/lists/*

# clone example repository
RUN git clone https://github.com/labDomolandes/ecofloc.git \
    && cd ecofloc \
    && make clean \
    && make \
    && make install

CMD ["/bin/bash"]