FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
        build-essential \
        python3-dev \
        musl-dev \
        git \
        rustc

COPY ./code/Energy-Aware-Entity-Resolution/requirements.txt /app/requirements.txt

WORKDIR /app
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt \
    && pip install git+https://github.com/dpkp/kafka-python.git

CMD ["/bin/bash"]