apiVersion: batch/v1
kind: Job
metadata:
  name: calculating-similarity
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: calculating-similarity
    spec:
      restartPolicy: OnFailure
      containers:
        - name: main
          image: kevinoulai/erctl:embedding
          imagePullPolicy: Always
          command: [/opt/venv/bin/python, /app/distributions/calculating_similarity_entry.py]
          args:
            - --mode
            - embedding-inference
          env:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: pipeline-config
              mountPath: /app/config/examples/config-embedding.yaml
              subPath: config.yaml
            - name: calculating-similarity-entry
              mountPath: /app/distributions/calculating_similarity_entry.py
              subPath: calculating_similarity_entry.py
            - name: embedding-common
              mountPath: /app/distributions/embedding_common.py
              subPath: embedding_common.py
            - name: pipeline-embedding-model-cache
              mountPath: /app/data
            - name: pipeline-buffer-data
              mountPath: /app/data/buffers
            - name: pipeline-reports
              mountPath: /app/reports
            - name: pipeline-buffer-utils
              mountPath: /app/utils/buffers.py
              subPath: buffers.py
            - name: pipeline-io
              mountPath: /app/utils/pipeline_io.py
              subPath: pipeline_io.py
            - name: config-io
              mountPath: /app/utils/config_io.py
              subPath: config_io.py
            - name: embedding-state
              mountPath: /app/state_io
      volumes:
        - name: pipeline-config
          configMap:
            name: er-pipeline-config
        - name: calculating-similarity-entry
          configMap:
            name: eaer-calculating-similarity-entry
        - name: embedding-common
          configMap:
            name: eaer-embedding-common
        - name: pipeline-embedding-model-cache
          persistentVolumeClaim:
            claimName: pipeline-embedding-model-cache-claim
        - name: pipeline-buffer-data
          persistentVolumeClaim:
            claimName: pipeline-buffer-data-claim
        - name: pipeline-buffer-utils
          configMap:
            name: eaer-kafka-buffers
        - name: pipeline-io
          configMap:
            name: eaer-pipeline-io
        - name: config-io
          configMap:
            name: eaer-config-io
        - name: embedding-state
          configMap:
            name: eaer-embedding-state
        - name: pipeline-reports
          persistentVolumeClaim:
            claimName: pipeline-reports-claim
