apiVersion: batch/v1
kind: Job
metadata:
  name: pipeline-init
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: pipeline-init
    spec:
      restartPolicy: OnFailure
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - fedora
      containers:
        - name: main
          image: kevinoulai/erctl:config
          imagePullPolicy: IfNotPresent
          command: [sh, /app/init.sh]
          env:
            - name: FALLBACK_MODE
              value: embedding-inference
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: pipeline-config
              mountPath: /app/config/examples/config-embedding.yaml
              subPath: config.yaml
            - name: pipeline-init-script
              mountPath: /app/init.sh
              subPath: init.sh
            - name: pipeline-buffer-data
              mountPath: /app/data/buffers
      volumes:
        - name: pipeline-config
          configMap:
            name: er-pipeline-config
        - name: pipeline-init-script
          configMap:
            name: eaer-pipeline-init
        - name: pipeline-buffer-data
          persistentVolumeClaim:
            claimName: pipeline-buffer-data-claim