apiVersion: batch/v1
kind: Job
metadata:
  name: normalization
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: normalization
    spec:
      restartPolicy: OnFailure
      containers:
        - name: main
          image: kevinoulai/erctl:normalization
          imagePullPolicy: Always
          command: [sh, -c]
          args:
            - |
              /opt/venv/bin/python /app/distributions/normalization_distribution.py --mode embedding-inference-inc --function normalization --raw_data /data/exp_datasets/4-1_dirty_dblp_acm/tableA.csv --data_source_A /data/exp_datasets/4-1_dirty_dblp_acm/tableA.csv --data_source_B /data/exp_datasets/4-1_dirty_dblp_acm/tableB.csv
          env:
            - name: CODECARBON_REPORT_PATH
              value: /app/reports/codecarbon/result/emissions.csv
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: pipeline-config
              mountPath: /app/config/examples/config-embedding.yaml
              subPath: config.yaml
            - name: normalization-distribution
              mountPath: /app/distributions/normalization_distribution.py
              subPath: normalization_distribution.py
            - name: pipeline-data
              mountPath: /app/Data_example
            - name: pipeline-buffer-data
              mountPath: /app/data/buffers
            - name: pipeline-reports
              mountPath: /app/reports
            - name: pipeline-buffer-utils
              mountPath: /app/utils/buffers.py
              subPath: buffers.py
            - name: codecarbon
              mountPath: /app/utils/codecarbon.py
              subPath: codecarbon.py
      volumes:
        - name: pipeline-config
          configMap:
            name: er-pipeline-config
        - name: normalization-distribution
          configMap:
            name: eaer-normalization-distribution
        - name: pipeline-data
          persistentVolumeClaim:
            claimName: pipeline-data-claim
        - name: pipeline-buffer-data
          persistentVolumeClaim:
            claimName: pipeline-buffer-data-claim
        - name: pipeline-reports
          persistentVolumeClaim:
            claimName: pipeline-reports-claim
        - name: pipeline-buffer-utils
          configMap:
            name: eaer-kafka-buffers
        - name: codecarbon
          configMap:
            name: eaer-codecarbon