apiVersion: v1
kind: Pod
metadata:
  name: printer
  labels:
    app.kubernetes.io/name: printer
    app: printer
spec:
  containers:
  - name: printer
    image: python:3.12-alpine
    command: ["python", "/app/print.py"]
    volumeMounts:
    - name: scripts
      mountPath: /app
      readOnly: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    ports:
    - containerPort: 8080
  volumes:
  - name: scripts
    configMap:
      name: pod-scripts
      items:
      - key: print.py
        path: print.py