apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-cg-features-claim
spec:
  resources:
    requests:
      storage: 10M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
