FROM kevinoulai/erctl:base AS builder

COPY code/Energy-Aware-Entity-Resolution/requirements/for_entries/requirements-base.txt \
     code/Energy-Aware-Entity-Resolution/requirements/for_entries/requirements-feature-index.txt \
     /app/requirements/for_entries/

RUN /opt/venv/bin/pip install --no-cache-dir \
    -r /app/requirements/for_entries/requirements-feature-index.txt

FROM kevinoulai/erctl:base

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

WORKDIR /app

COPY --from=builder /opt/venv /opt/venv

COPY ./code/Energy-Aware-Entity-Resolution/pipeline/feature_index_construction.py /app/pipeline/feature_index_construction.py
COPY ./code/Energy-Aware-Entity-Resolution/pipeline/candidate_enumeration.py /app/pipeline/candidate_enumeration.py
COPY ./code/Energy-Aware-Entity-Resolution/models/cg_index.py /app/models/cg_index.py
COPY ./code/Energy-Aware-Entity-Resolution/pipeline/cg_feature_extraction.py /app/pipeline/cg_feature_extraction.py
