FROM kevinoulai/erctl:min

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

WORKDIR /app

COPY ./code/Energy-Aware-Entity-Resolution/pipeline/feature_index_construction.py /app/pipeline/feature_index_construction.py
COPY ./code/Energy-Aware-Entity-Resolution/pipeline/candidate_enumeration.py /app/pipeline/candidate_enumeration.py
COPY ./code/Energy-Aware-Entity-Resolution/models/cg_index.py /app/models/cg_index.py
COPY ./code/Energy-Aware-Entity-Resolution/pipeline/cg_feature_extraction.py /app/pipeline/cg_feature_extraction.py