FROM erctl:base1.1

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

WORKDIR /app

COPY ./code/Energy-Aware-Entity-Resolution/pipeline /app/pipeline
COPY ./code/Energy-Aware-Entity-Resolution/models /app/models
COPY ./code/Energy-Aware-Entity-Resolution/utils /app/utils

CMD ["/bin/bash", "-c", "source /opt/venv/bin/activate && tail -f /dev/null"]