FROM kevinoulai/erctl:base AS builder

COPY code/Energy-Aware-Entity-Resolution/requirements/for_entries/requirements-base.txt \
     code/Energy-Aware-Entity-Resolution/requirements/for_entries/requirements-graph.txt \
     /app/requirements/for_entries/

RUN /opt/venv/bin/pip install --no-cache-dir \
    -r /app/requirements/for_entries/requirements-graph.txt

FROM kevinoulai/erctl:base

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

WORKDIR /app

COPY --from=builder /opt/venv /opt/venv

COPY ./code/Energy-Aware-Entity-Resolution/pipeline/graph_construction.py /app/pipeline/graph_construction.py
COPY ./code/Energy-Aware-Entity-Resolution/pipeline/random_walk.py /app/pipeline/random_walk.py
COPY ./code/Energy-Aware-Entity-Resolution/pipeline/sampler.py /app/pipeline/sampler.py
COPY ./code/Energy-Aware-Entity-Resolution/models/representation_graph.py /app/models/representation_graph.py
