FROM erctl:min

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

WORKDIR /app

COPY ./code/Energy-Aware-Entity-Resolution/pipeline/normalization.py /app/pipeline/normalization.py
COPY ./code/Energy-Aware-Entity-Resolution/distributions/normalization_distribution.py /app/distributions/normalization_distribution.py