FROM kevinoulai/erctl:base AS builder

COPY ./code/Energy-Aware-Entity-Resolution/requirements/for_entries/requirements-base.txt \
     ./code/Energy-Aware-Entity-Resolution/requirements/for_entries/requirements-kafka.txt \
     /app/requirements/for_entries/

RUN /opt/venv/bin/pip install --no-cache-dir \
        -r /app/requirements/for_entries/requirements-kafka.txt \
    && rm -rf /root/.cache/pip

FROM kevinoulai/erctl:base

WORKDIR /app

COPY --from=builder /opt/venv /opt/venv
