# FROM erctl:base1.2.1 AS builder

# ENV PIP_NO_CACHE_DIR=1
# ENV PYTHONDONTWRITEBYTECODE=1

# WORKDIR /app

# COPY code/Energy-Aware-Entity-Resolution/requirements-bert.txt /app/requirements.txt

# RUN /opt/venv/bin/pip install --no-cache-dir -r /app/requirements.txt
FROM kevinoulai/erctl:full

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

WORKDIR /app

# COPY --from=builder /opt/venv /opt/venv

COPY ./code/Energy-Aware-Entity-Resolution/pipeline /app/pipeline
COPY ./code/Energy-Aware-Entity-Resolution/models /app/models
COPY ./code/Energy-Aware-Entity-Resolution/distributions/bert_distribution.py /app/distributions/bert_distribution.py
COPY ./code/Energy-Aware-Entity-Resolution/Data_example/bert /app/Data_example/bert
