apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pipeline-bert-model-claim
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /var/lib/eaer/pv/pipeline-bert-model-claim
  claimRef:
    namespace: argo
    name: pipeline-bert-model-claim
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - server2-labo
