apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-reports-claim
  namespace: argo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 50Mi
