apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-decision-evaluation-cache-claim
  namespace: argo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 100Mi