apiVersion: apps/v1
kind: Deployment
metadata:
  name: bert
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bert
  template:
    metadata:
      labels:
        app: bert
    spec:
      containers:
      - name: bert
        image: erctl:bert1.1
        imagePullPolicy: Never
        command: ["/bin/bash", "-c", "source /opt/venv/bin/activate && tail -f /dev/null"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        - containerPort: 8081