apiVersion: apps/v1
kind: Deployment
metadata:
  name: decision-making
spec:
  selector:
    matchLabels:
      app: decision-making
  template:
    metadata:
      labels:
        app: decision-making
    spec:
      containers:
      - name: decision-making
        image: python:3.12-alpine
        command: ["python", "/app/decision_making.py"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
