apiVersion: apps/v1
kind: Deployment
metadata:
  name: bert
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bert
  template:
    metadata:
      labels:
        app: bert
    spec:
      containers:
      - name: bert
        image: kevinoulai/erctl:bert
        imagePullPolicy: Always # In dev, needed to update the code
        command: ["/bin/bash", "-c", "source /opt/venv/bin/activate && python ./distributions/bert_distribution.py"]
        volumeMounts:
        - name: bert-distribution
          mountPath: /app/distributions/bert_distribution.py
          subPath: bert_distribution.py
        resources:
          limits:
            memory: "4Gi"
            cpu: "500m"
          requests:
            memory: "2Gi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        - containerPort: 8081
      volumes:
      - name: bert-distribution
        configMap:
          name: eaer-bert-distribution