apiVersion: apps/v1
kind: Deployment
metadata:
  name: bert-training
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bert-training
  template:
    metadata:
      labels:
        app: bert-training
    spec:
      containers:
      - name: bert-training
        image: eaer-k8s:slim
        imagePullPolicy: Never
        command: ["python", "/scripts/BERT_training.py"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "32Mi"
            cpu: "50m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: scripts
          mountPath: /scripts
          readOnly: true
        - name: pipeline-bert-model-claim
          mountPath: /pipeline
      volumes:
      - name: scripts
        configMap:
          name: bert-training
          items:
          - key: BERT_training.py
            path: BERT_training.py
      - name: pipeline-bert-model-claim
        persistentVolumeClaim:
          claimName: pipeline-bert-model-claim