apiVersion: apps/v1
kind: Deployment
metadata:
  name: bert-inference
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bert-inference
  template:
    metadata:
      labels:
        app: bert-inference
    spec:
      containers:
      - name: bert-inference
        image: eaer-k8s:latest
        imagePullPolicy: Never
        command: ["python", "/app/BERT_inference.py"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "32Mi"
            cpu: "50m"
        ports:
        - containerPort: 8080
        - containerPort: 8081
        - containerPort: 8082
        volumeMounts:
        - name: scripts
          mountPath: /app
          readOnly: true
        - name: pipeline-bert-model-claim
          mountPath: /pipeline
      volumes:
      - name: scripts
        configMap:
          name: bert-inference
          items:
          - key: BERT_inference.py
            path: BERT_inference.py
      - name: pipeline-bert-model-claim
        persistentVolumeClaim:
          claimName: pipeline-bert-model-claim