apiVersion: apps/v1
kind: Deployment
metadata:
  name: bert
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bert
  template:
    metadata:
      labels:
        app: bert
    spec:
      containers:
      - name: bert
        image: eaer-k8s:slim
        imagePullPolicy: Never
        command: ["python", "/scripts/BERT_evaluation.py"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        - containerPort: 8081
        volumeMounts:
        - name: scripts
          mountPath: /scripts
          readOnly: true
      volumes:
      - name: scripts
        configMap:
          name: bert
          items:
          - key: BERT_evaluation.py
            path: BERT_evaluation.py
          - key: BERT_training.py
            path: BERT_training.py
          - key: BERT_inference.py
            path: BERT_inference.py