apiVersion: apps/v1
kind: Deployment
metadata:
  name: normalization
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: normalization
  template:
    metadata:
      labels:
        app: normalization
    spec:
      containers:
      - name: normalization
        image: kevinoulai/erctl:normalization
        imagePullPolicy: Always # In dev, needed to update the code
        command: ["/bin/bash", "-c", "source /opt/venv/bin/activate && python /app/distributions/normalization_distribution.py"]
        volumeMounts:
        - name: normalization-distribution
          mountPath: /app/distributions/normalization_distribution.py
          subPath: normalization_distribution.py
        securityContext:
          privileged: true
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
      volumes:
      - name: normalization-distribution
        configMap:
          name: eaer-normalization-distribution



