apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph-construction
spec:
  selector:
    matchLabels:
      app: graph-construction
  template:
    metadata:
      labels:
        app: graph-construction
    spec:
      containers:
      - name: graph-construction
        image: python:3.12-alpine
        command: ["python", "/app/graph_construction.py"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
