apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedding-training
spec:
  selector:
    matchLabels:
      app: embedding-training
  template:
    metadata:
      labels:
        app: embedding-training
    spec:
      containers:
      - name: embedding-training
        image: python:3.12-alpine
        command: ["python", "/app/embedding_training.py"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
