apiVersion: apps/v1
kind: Deployment
metadata:
  name: normalization
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: normalization
  template:
    metadata:
      labels:
        app: normalization
    spec:
      containers:
      - name: normalization
        image: erctl:normalization1.1
        imagePullPolicy: Never
        command: ["/bin/bash", "-c", "source /opt/venv/bin/activate && tail -f /dev/null"]
        securityContext:
          privileged: true
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080



