apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-index-construction
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: feature-index-construction
  template:
    metadata:
      labels:
        app: feature-index-construction
    spec:
      containers:
      - name: feature-index-construction
        image: eaer-k8s:slim
        imagePullPolicy: Never
        command: ["python", "/scripts/feature_index_construction.py"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "32Mi"
            cpu: "50m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: scripts
          mountPath: /scripts
          readOnly: true
        - name: pipeline-cg-features-claim
          mountPath: /pipeline
      volumes:
      - name: scripts
        configMap:
          name: feature-index-construction
          items:
          - key: feature_index_construction.py
            path: feature_index_construction.py
      - name: pipeline-cg-features-claim
        persistentVolumeClaim:
          claimName: pipeline-cg-features-claim