apiVersion: v1
kind: Service
metadata:
  name: service-candidate-enumeration
spec:
  selector:
    app: candidate-enumeration
  ports:
  - name: cg-feature-extraction-listener
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: feature-index-construction-listener
    protocol: TCP
    port: 81
    targetPort: 8081