apiVersion: v1
kind: Service
metadata:
  name: service-calculating-similarity
spec:
  selector:
    app: calculating-similarity
  ports:
  - name: candidate-enumeration-listener
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: embedding-training-listener
    protocol: TCP
    port: 81
    targetPort: 8081